defaults:
  # - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

base:
  videoUrl: video_url.txt                   #文件里面保存要下载的YouTube的视频网址

sperker_info:
  ID: p132                                  #说话人ID，用于目录命名
  index: 6                                  #说话人索引

demucs:
single_speaker:
  HF_Access_Tokens: ""   #填写huggingface的Access Tokens
  model_name: "pyannote/speaker-diarization-3.1"
  use_cuda: True

slicer:
  threshold: -30                            #静音检测的分贝阈值
  min_length: 5000                          #每个切片音频片段所需的最小毫秒数
  min_interval: 300                         #用于切割静音部分的最小毫秒数
  hop_size: 20                              #帧长度（毫秒）
  max_sil_kept: 5000                        #在切片音频片段周围保留的最大静音长度，以毫秒表示


dir:
  root: .temp                               #设置项目临时文件目录
  youtube: ${dir.root}/youtube              #目录保存YouTube上下载的音频文件
  segment: ${dir.root}/segment              #目录保存切片后保存的文件
  solo_voice: ${dir.root}/solo_voice        #目录保存经过筛选出的单人说话的音频
  Speech_V: ${dir.root}/Speech_V            #目录从solo_voice复制说话人说话最多的音频
  results: results/${sperker_info.ID}       #最终数据集的保存位置
